plugins { id 'net.fabricmc.fabric-loom' version '1.17.20' }
base { archivesName = 'hoi-client' }
dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
    implementation project(':protocol')
    include project(':protocol')
}
processResources {
    inputs.property 'version', project.version
    filesMatching('fabric.mod.json') { expand version: project.version }
}
fabricApi {
    configureTests {
        createSourceSet = true
        modId = 'hoi-client-test'
        enableGameTests = false
        enableClientGameTests = true
    }
}
